WITH RECURSIVE cte AS (
    SELECT id, PARENT_ID, 1 AS n
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT ed.ID, ed.PARENT_ID, n + 1
    FROM ECOLI_DATA ed INNER JOIN cte ON ed.PARENT_ID = cte.ID
)
SELECT COUNT(*) COUNT, n GENERATION
FROM ECOLI_DATA ed JOIN cte ON ed.ID = cte.id
WHERE NOT EXISTS (SELECT ID FROM ECOLI_DATA WHERE ed.ID = PARENT_ID)
GROUP BY n
ORDER BY n