SELECT ID, GENOTYPE, (SELECT GENOTYPE FROM ECOLI_DATA WHERE ed.PARENT_ID = ID) PARENT_GENOTYPE
FROM ECOLI_DATA ed
WHERE GENOTYPE & (SELECT GENOTYPE FROM ECOLI_DATA WHERE ed.PARENT_ID = ID) = (SELECT GENOTYPE FROM ECOLI_DATA WHERE ed.PARENT_ID = ID)
ORDER BY ID