WITH a AS (
    SELECT CODE
    FROM SKILLCODES 
    WHERE NAME = 'C#'
), b AS (
    SELECT CODE
    FROM SKILLCODES 
    WHERE NAME = 'Python'
)
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS, a, b
WHERE SKILL_CODE & a.CODE = a.CODE OR SKILL_CODE & b.CODE = b.CODE
ORDER BY ID;