SELECT YEAR(DIFFERENTIATION_DATE) YEAR
    , (SELECT MAX(SIZE_OF_COLONY) FROM ECOLI_DATA WHERE YEAR(e.DIFFERENTIATION_DATE) = YEAR(DIFFERENTIATION_DATE)) - SIZE_OF_COLONY AS YEAR_DEV
    , ID
FROM ECOLI_DATA e
ORDER BY YEAR, YEAR_DEV